version: '3.9'

services:
  database:
    image: 'postgres:latest'
    restart: always

    ports:
      - 5432:5432

    env_file:
      - .env

    network_mode: "host"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4

    depends_on:
      - database
    env_file:
      - .env
    ports:
      - 105:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
