version: '3.9'

services:
  database:
    image: 'postgres:latest'
    restart: always

    ports:
      - 5432:5432

    env_file:
      - .env

    volumes:
      - ./db-data:/var/lib/postgresql/data/

  application:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - .env/:/.env
    depends_on:
      - database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}



